apiVersion: v1
kind: Service
metadata:
  name: dataaccessor-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30800
  selector:
    app: dataaccessor-pod

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataaccessor-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataaccessor-pod
  template:
    metadata:
      labels:
        app: dataaccessor-pod
    spec:
      containers:
        - name: dataaccessor
          image: ghcr.io/hounsvad/sem7dataaccessor:latest
          ports:
            - containerPort: 80


