apiVersion: v1
kind: ConfigMap
metadata:
  name: ingest-config
data:
  CopernicusSearchInterval: "MONTHS"
  DataAPI: "https://apihub.copernicus.eu/apihub"
  SearchArea: "POLYGON((10.668743 55.503501,10.668743 55.233606,10.192956 55.233606,10.192956 55.503501,10.668743 55.503501))"
  APIAuth: "Basic ZnJob3UxODp1RDQ0JXpjNVhqJGZhSEJqaw=="
  KafkaAddress: "kafka-service:9092"
  KafkaTopic: "NDVI"
  hdfsImageIngestPath: "/app/img"
  hdfsImageIngestRedImage: "Rout.bmp"
  hdfsImageIngestNirImage: "IRout.bmp"
  kafkaURL: "kafka-service:9092"
  ndviPixelIngestTopic: "img"
  sparkAppName: "ImageProcessor"
  sparkMasterURL: "spark://spark-master:7077"
  sparkMaxMemory: "2g"
  sparkCheckpointLocationURL: "hdfs://hdfs-namenode:9000/spark-checkpoints"
  pythonProcessor: "/app/PythonProcessor.py"
  pythonImg: "/app/img.py"
  JAVA_HOME: "/usr/lib/jvm/java-11-openjdk-amd64"