apiVersion: v1
kind: Service
metadata:
  name: ingest
  labels:
    name: ingest
spec:
  selector:
    app: ingest
  ports:
  - port: 81
    targetPort: 81
    nodePort: 30081
    protocol: TCP
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingest-deployment
spec:
  selector:
    matchLabels:
      app: ingest-pod
  template:
    metadata:
      labels:
        app: ingest-pod
    spec:
      hostname: ingest
      containers:
      - name: ingest
        image: ghcr.io/hounsvad/sem7ingest:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 81
        envFrom:
          - configMapRef:
              name: ingest-config
