apiVersion: v1
kind: Service
metadata:
  name: spark-master
spec:
  selector:
    app: spark-master-pod
  ports:
  - port: 7077
    targetPort: 7077
  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master-deployment
spec:
  selector:
    matchLabels:
      app: spark-master-pod
  template:
    metadata:
      labels:
        app: spark-master-pod
    spec:
      hostname: spark-master
      containers:
      - name: master-container
        image: bde2020/spark-master:3.1.1-hadoop3.2
        ports:
        - containerPort: 7077
        env:
          - name: INIT_DAEMON_STEP
            value: "setup_spark"
          - name: SPARK_MASTER_PORT
            value: "7077"
#          - name: SPARK_SUBMIT_ARGS
#            value: "--packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.1.2"
#          - name: ENABLE_INIT_DAEMON
#            value: "false"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spark-worker-pod
  template:
    metadata:
      labels:
        app: spark-worker-pod
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - spark-worker-pod
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: worker-container
        image: bde2020/spark-worker:3.1.1-hadoop3.2
        env:
          - name: SPARK_MASTER
            value: "spark://spark-master:7077"
